### ISSUE TITLE
I2S slave output

### ISSUE THREAD

**Issue by myreauks** [elehobica/pico_spdif_rx#12]
Hi again!

I have been bothering you a lot on this repository already, there is still one thing I am wondering.
I have been trying to play with combining code from your pico_spdif_rx and malacalypses rp2040_i2s_example (https://github.com/malacalypse/rp2040_i2s_example) to create a spdif to i2s slave output. However, I have again pushed myself into a corner and none of the things I have tried are working. 

Do you have any pointers for me to proceed on converting the project to allow I2S slave output, or is this a very challenging task to get spdif and i2s output synced if the pico is not acting as a master? While I have started learning pio, it is still very cryptic for me.
I had the I2S example working before with a PCM5102, but would like to change to my ADAU1701 board for the DSP functionalities and this requires for me to use the ADAU1701 as a master.

Any help would be greatly appreciated. Or if this is not something you are not interested in pursuing, I will slowly learn and commit to figuring it out by myself.

Best,
Miro

**Comment by elehobica** [comment]
Hello.

Thank you for the trial to expand the usage of this library.
If I understand your post correctly, the audio processor receives audio data from SPDIF as an I2S master, thus sending BCK and LRCK to the slave, and SPDIF side plays an I2S slave role as if it were ADC. (please tell me if I'm wrong)

The problem when SPDIF side cannot be an I2S master is precise rate matching between SPDIF and audio clock from the processor. Generally, since SPDIF receiver is always a slave of SPDIF transmitter, it cannot meet its data rate for other than SPDIF transmitter.

Therefore, you will need to introduce fractional delay filters (Farrow Filter) or something equivalent to absorb the slight difference the data rate between SPDIF side and the processor side.
Or if you can permit the constant dropout of audio data for temporary testing purpose, to omit or duplicate audio samples depending on the FIFO count could be one option.

This is very common issue when various source audio data should be synchronized with the certain fixed data rate, and you will need to prepare additional treatment or processing block for it.

I hope this could be a hint of your case.

Best Regards

**Comment by myreauks** [comment]
Ah wow, thanks for the great explanation, I'll have to bite into this bit by bit. I will close this for issue now and put in a pull request in the eventuality I will get all this working.
Thanks!
