### ISSUE TITLE
Accessing channel bytes

### ISSUE THREAD

**Issue by myreauks** [elehobica/pico_spdif_rx#7]
Hi again!
I have been tinkering with the code for a while now trying to access the bits from SPDIF signal that LG uses to communicate their TV volume as mentioned in this guide:
https://github.com/hifiberry/hifiberry-dsp/blob/master/doc/reverse-engineering-lg.md

However, as I am quite the novice with handling bytes and bits, I am not getting anywhere with my efforts. If it is not too much trouble, could you point me to the right way? So much I have found out that this the check_block() function is probably to one I need to modify to access the correct bytes?

This code is used to access some of the bytes, but I'm quite not sure how it works and which bytes it is accessing?
```
// VUCP handling
// C bits (heading 32bit only)
if (i % 2 == 0 && cbit_mask) { // using even sub frame of heading 32 frames of each block
	if (buff[i] & (0x1<<30)) {
		block_cbits |= cbit_mask;
	}
	cbit_mask <<= 1; // will become 0 after 32 bits are collected, and stop the if()
 }
```

Best regards,
Miro

**Comment by elehobica** [comment]
Hi, myreauks

Thanks again for this post.
Actually, after you mentioned about LGTV, I've also investigated info about how the volume control is done through _optical_ and found this:

https://github.com/hifiberry/hifiberry-dsp/blob/master/doc/reverse-engineering-lg.md

According to it, the upper bits of C code seem to be used for volume and mute information.
Currently this pico_spdif_rx library handles only heading 32bit (thus LSB) of C bits, therefore, to support additional info, I think this library should be expanded to handle whole 192 bits.

I'd like to support full C bits and now I'm considering how the _get_ function should be. I estimate maybe you'll see it in a few days.

Otherwise, if you'd like to revise the code on temporary basis, then preparing 6 words (32bit x 6) of `block_cbits` and assigning bits from input stream for up to 192 positions should be done. 

Best Regards

**Comment by myreauks** [comment]
Hi!
Great stuff. That hifiberry doc is the one I have been looking at too. I'm Interested in seeing your solution as it is also a great learning point for me to see how you solve it. I have not yet managed to do it, but if I have time today I'll try to do it the way you said.

**Comment by elehobica** [comment]
Hi, I created [expand-c-bits-support-to-192bits](https://github.com/elehobica/pico_spdif_rx/tree/expand-c-bits-support-to-192bits) branch. now you can get c bits up to 192 bits with byte unit. If the information of [reverse-engineering](https://github.com/hifiberry/hifiberry-dsp/blob/master/doc/reverse-engineering-lg.md) is correct, you will be able to get volume and mute signal as below:

```
uint16_t c_bits;
spdif_rx_get_c_bits(&c_bits, sizeof(c_bits), 7); // to get byte 7, 8
uint8_t volume = (c_bits & 0x07F0) >> 4; // 0 ~ 100
bool mute = (cbits & 0x0800) != 0;
```

It's not verified because I don't have LGTV. I hope it will work.

**Comment by myreauks** [comment]
Hi!
Thanks a lot. Seems promising.
Using the following code, I am just getting this as printout:
Volume = 0. I wonder what might be the problem.

```
    while (true) {
        spdif_rx_status_t status = spdif_rx_get_status();
        if (status == SPDIF_RX_STATUS_STABLE) {
            uint32_t samp_freq = spdif_rx_get_samp_freq();
            float samp_freq_actual = spdif_rx_get_samp_freq_actual();

            uint16_t c_bits;
            spdif_rx_get_c_bits(&c_bits, sizeof(c_bits), 7); // to get byte 7, 8
            uint8_t volume = (c_bits & 0x07F0) >> 4; // 0 ~ 100
            bool mute = (c_bits & 0x0800) != 0;
            printf("Volume = %d\n", volume);

            // uint32_t c_bits;
            // spdif_rx_get_c_bits(&c_bits, sizeof(c_bits), 0);
            // printf("Samp Freq = %d Hz (%7.4f KHz)\n", samp_freq, samp_freq_actual / 1e3);
            // printf("c_bits = 0x%08x\n", c_bits);
            // printf("parity errors = %d\n", spdif_rx_get_parity_err_count());
        } else if (status == SPDIF_RX_STATUS_NO_SIGNAL) {
            printf("stable sync not detected\n");
            spdif_rx_search();
        }
        tight_loop_contents();
        sleep_ms(1000);
    }
```

I was trying to read all the 24 channel bytes with the following code but I am getting only the first eight bytes right and everything after that is zeros:

```
spdif_rx_get_c_bits(&c_bits, sizeof(c_bits), 0);
printf("SPDIF C bits = 0x%08x", c_bits);
spdif_rx_get_c_bits(&c_bits, sizeof(c_bits), 8);
printf("%08x", c_bits);
spdif_rx_get_c_bits(&c_bits, sizeof(c_bits), 16);
printf("%08x\n", c_bits);
```

Maybe there is something wrong with my code?
I'll keep trying stuff later.

**Comment by elehobica** [comment]
Okay, I'll check my code again.
To see whole 192 bits, please try following:
```
uint32_t c_bits[6];
spdif_rx_get_c_bits(c_bits, sizeof(c_bits), 0);
for (int i = 0; i < 6; i++) {
    printf("%d: %08x\n", i, c_bits[i]);
}
```

**Comment by myreauks** [comment]
Thanks for the update.
The output I am getting with this code is the following:
```
0: 02000c04
1: 00000000
2: 00000000
3: 00000000
4: 00000000
5: 00000000
```

Edit:
Never mind the previous, now I got it working. I had to change the output of my TV to only Optical and not Internal Speakers + Optical to get the volume output through optical. Now I am getting this and the bits in the fourth array change when changing volume on the TV.
```
0: 02000c04
1: 7f048a60
2: 00000000
3: 00000190
4: 00000000
5: 00000000
```

**Comment by elehobica** [comment]
congratulations! so, above means volume = 7, right?

**Comment by myreauks** [comment]
Yes, exactly! 
Now I got the volume working with the exact code you posted in the first update. Very nice.
This is now printing the same value as my TV volume is set to:
```
            uint16_t c_bits;
            spdif_rx_get_c_bits(&c_bits, sizeof(c_bits), 7); // to get byte 7, 8
            uint8_t volume = (c_bits & 0x07F0) >> 4; // 0 ~ 100
            bool mute = (c_bits & 0x0800) != 0;

            printf("Volume: %d\n", volume);
```

In the end it was just a matter of TV audio settings.
Thanks a lot!

**Comment by elehobica** [comment]
you're welcome. I'll merge the branch into main soon.
